import { AppState, AppSettings } from '@/types/index';

const defaultSettings: AppSettings = {
  companyName: 'TalentFlow Inc.',
  companyWebsite: 'https://talentflow.io',
  emailNotifications: true,
  theme: 'light',
};

export const seedData: AppState = {
  settings: defaultSettings,
  currentUser: {
    id: 'user-1',
    name: 'Alex Rivera',
    email: 'alex@talentflow.io',
    role: 'admin',
    department: 'HR',
    joinedAt: '2023-01-15T00:00:00Z',
    activeInterviews: 3,
  },
  jobs: [
    {
      id: 'job-1',
      title: 'Senior Frontend Engineer',
      department: 'Engineering',
      location: 'San Francisco, CA',
      type: 'full_time',
      status: 'open',
      description: 'We are looking for a Senior Frontend Engineer to join our growing team.',
      requirements: ['5+ years React', 'TypeScript', 'CSS-in-JS'],
      salary: { min: 140000, max: 180000, currency: 'USD' },
      experienceLevel: 'senior',
      createdAt: '2024-01-10T00:00:00Z',
      updatedAt: '2024-01-10T00:00:00Z',
      applicantCount: 24,
      openings: 2,
    },
    {
      id: 'job-2',
      title: 'Product Manager',
      department: 'Product',
      location: 'New York, NY',
      type: 'full_time',
      status: 'open',
      description: 'Seeking an experienced Product Manager to drive product strategy.',
      requirements: ['3+ years PM experience', 'Agile', 'Data-driven'],
      salary: { min: 120000, max: 160000, currency: 'USD' },
      experienceLevel: 'mid',
      createdAt: '2024-01-12T00:00:00Z',
      updatedAt: '2024-01-12T00:00:00Z',
      applicantCount: 18,
      openings: 1,
    },
    {
      id: 'job-3',
      title: 'UX Designer',
      department: 'Design',
      location: 'Remote',
      type: 'remote',
      status: 'published',
      description: 'Join our design team to craft beautiful user experiences.',
      requirements: ['Figma', 'User Research', 'Prototyping'],
      salary: { min: 100000, max: 130000, currency: 'USD' },
      experienceLevel: 'mid',
      createdAt: '2024-01-15T00:00:00Z',
      updatedAt: '2024-01-15T00:00:00Z',
      applicantCount: 31,
      openings: 1,
    },
    {
      id: 'job-4',
      title: 'Backend Engineer',
      department: 'Engineering',
      location: 'Austin, TX',
      type: 'full_time',
      status: 'draft',
      description: 'Looking for a skilled Backend Engineer to build scalable APIs.',
      requirements: ['Node.js', 'PostgreSQL', 'AWS'],
      salary: { min: 130000, max: 170000, currency: 'USD' },
      experienceLevel: 'senior',
      createdAt: '2024-01-18T00:00:00Z',
      updatedAt: '2024-01-18T00:00:00Z',
      applicantCount: 12,
      openings: 2,
    },
    {
      id: 'job-5',
      title: 'Data Analyst',
      department: 'Analytics',
      location: 'Chicago, IL',
      type: 'full_time',
      status: 'closed',
      description: 'Seeking a Data Analyst to derive insights from complex datasets.',
      requirements: ['SQL', 'Python', 'Tableau'],
      salary: { min: 90000, max: 120000, currency: 'USD' },
      experienceLevel: 'entry',
      createdAt: '2024-01-05T00:00:00Z',
      updatedAt: '2024-01-20T00:00:00Z',
      applicantCount: 45,
      openings: 1,
    },
  ],
  candidates: [
    {
      id: 'cand-1',
      name: 'Jordan Smith',
      email: 'jordan.smith@email.com',
      phone: '+1 (555) 234-5678',
      location: 'San Francisco, CA',
      jobId: 'job-1',
      jobTitle: 'Senior Frontend Engineer',
      status: 'interview',
      skills: ['React', 'TypeScript', 'GraphQL', 'CSS'],
      experience: 6,
      notes: 'Strong technical background, excellent communication skills.',
      rating: 4,
      appliedAt: '2024-01-15T10:00:00Z',
      updatedAt: '2024-01-22T14:00:00Z',
      tags: ['top-candidate', 'fast-response'],
    },
    {
      id: 'cand-2',
      name: 'Morgan Lee',
      email: 'morgan.lee@email.com',
      phone: '+1 (555) 345-6789',
      location: 'New York, NY',
      jobId: 'job-2',
      jobTitle: 'Product Manager',
      status: 'screening',
      skills: ['Agile', 'Jira', 'Data Analysis', 'Roadmapping'],
      experience: 4,
      notes: 'Impressive portfolio of shipped products.',
      rating: 4,
      appliedAt: '2024-01-16T09:00:00Z',
      updatedAt: '2024-01-20T11:00:00Z',
      tags: ['experienced'],
    },
    {
      id: 'cand-3',
      name: 'Casey Johnson',
      email: 'casey.j@email.com',
      phone: '+1 (555) 456-7890',
      location: 'Remote',
      jobId: 'job-3',
      jobTitle: 'UX Designer',
      status: 'offer',
      skills: ['Figma', 'User Research', 'Prototyping', 'CSS'],
      experience: 5,
      notes: 'Exceptional portfolio, great culture fit.',
      rating: 5,
      appliedAt: '2024-01-17T08:00:00Z',
      updatedAt: '2024-01-25T16:00:00Z',
      tags: ['top-candidate', 'design-expert'],
    },
    {
      id: 'cand-4',
      name: 'Riley Brown',
      email: 'riley.brown@email.com',
      location: 'Austin, TX',
      jobId: 'job-1',
      jobTitle: 'Senior Frontend Engineer',
      status: 'new',
      skills: ['Vue.js', 'JavaScript', 'Node.js'],
      experience: 3,
      appliedAt: '2024-01-20T14:00:00Z',
      updatedAt: '2024-01-20T14:00:00Z',
      tags: [],
    },
    {
      id: 'cand-5',
      name: 'Taylor Davis',
      email: 'taylor.d@email.com',
      phone: '+1 (555) 567-8901',
      location: 'Chicago, IL',
      jobId: 'job-5',
      jobTitle: 'Data Analyst',
      status: 'hired',
      skills: ['SQL', 'Python', 'Tableau', 'Excel'],
      experience: 2,
      notes: 'Great analytical skills, quick learner.',
      rating: 4,
      appliedAt: '2024-01-08T09:00:00Z',
      updatedAt: '2024-01-28T10:00:00Z',
      tags: ['hired'],
    },
    {
      id: 'cand-6',
      name: 'Sam Wilson',
      email: 'sam.wilson@email.com',
      location: 'Seattle, WA',
      jobId: 'job-4',
      jobTitle: 'Backend Engineer',
      status: 'rejected',
      skills: ['Python', 'Django', 'PostgreSQL'],
      experience: 2,
      appliedAt: '2024-01-19T11:00:00Z',
      updatedAt: '2024-01-24T09:00:00Z',
      tags: [],
    },
  ],
  interviews: [
    {
      id: 'int-1',
      candidateId: 'cand-1',
      candidateName: 'Jordan Smith',
      jobId: 'job-1',
      jobTitle: 'Senior Frontend Engineer',
      interviewerId: 'user-2',
      interviewerName: 'Sam Chen',
      type: 'technical',
      status: 'scheduled',
      scheduledAt: '2024-02-05T14:00:00Z',
      duration: 60,
      location: 'Google Meet',
      notes: 'Focus on React architecture and TypeScript.',
    },
    {
      id: 'int-2',
      candidateId: 'cand-2',
      candidateName: 'Morgan Lee',
      jobId: 'job-2',
      jobTitle: 'Product Manager',
      interviewerId: 'user-3',
      interviewerName: 'Jordan Park',
      type: 'phone',
      status: 'scheduled',
      scheduledAt: '2024-02-06T10:00:00Z',
      duration: 30,
      notes: 'Initial screening call.',
    },
    {
      id: 'int-3',
      candidateId: 'cand-3',
      candidateName: 'Casey Johnson',
      jobId: 'job-3',
      jobTitle: 'UX Designer',
      interviewerId: 'user-1',
      interviewerName: 'Alex Rivera',
      type: 'video',
      status: 'completed',
      scheduledAt: '2024-01-28T15:00:00Z',
      duration: 45,
      feedback: 'Excellent candidate, highly recommend moving forward.',
      rating: 5,
    },
  ],
  team: [
    {
      id: 'user-1',
      name: 'Alex Rivera',
      email: 'alex@talentflow.io',
      role: 'admin',
      department: 'HR',
      joinedAt: '2023-01-15T00:00:00Z',
      activeInterviews: 3,
    },
    {
      id: 'user-2',
      name: 'Sam Chen',
      email: 'sam@talentflow.io',
      role: 'hiring_manager',
      department: 'Engineering',
      joinedAt: '2023-03-20T00:00:00Z',
      activeInterviews: 5,
    },
    {
      id: 'user-3',
      name: 'Jordan Park',
      email: 'jordan@talentflow.io',
      role: 'recruiter',
      department: 'HR',
      joinedAt: '2023-06-01T00:00:00Z',
      activeInterviews: 8,
    },
    {
      id: 'user-4',
      name: 'Casey Morgan',
      email: 'casey@talentflow.io',
      role: 'interviewer',
      department: 'Design',
      joinedAt: '2023-09-10T00:00:00Z',
      activeInterviews: 2,
    },
  ],
};
