import type { AppState } from '@/types/index';

export const seedData: AppState = {
  currentUser: {
    id: 'user-1',
    name: 'Alex Johnson',
    email: 'alex@company.com',
    role: 'admin',
    department: 'Engineering',
    isActive: true,
    joinedDate: '2022-01-15T00:00:00.000Z',
  },
  settings: {
    companyName: 'TalentFlow Inc.',
    timezone: 'America/New_York',
    dateFormat: 'MM/DD/YYYY',
    emailNotifications: true,
    slackIntegration: false,
  },
  jobs: [
    {
      id: 'job-1',
      title: 'Senior Frontend Engineer',
      department: 'Engineering',
      location: 'Remote',
      type: 'full_time',
      experienceLevel: 'senior',
      status: 'open',
      description: 'We are looking for a Senior Frontend Engineer to join our growing team.',
      requirements: ['5+ years experience', 'React expertise', 'TypeScript proficiency'],
      salary: { min: 130000, max: 170000, currency: 'USD' },
      postedDate: '2024-01-10T00:00:00.000Z',
      hiringManagerId: 'user-1',
      teamMemberIds: ['user-2'],
      tags: ['react', 'typescript', 'frontend'],
    },
    {
      id: 'job-2',
      title: 'Product Manager',
      department: 'Product',
      location: 'New York, NY',
      type: 'full_time',
      experienceLevel: 'mid',
      status: 'open',
      description: 'Seeking an experienced Product Manager to drive product strategy.',
      requirements: ['3+ years PM experience', 'Strong analytical skills', 'Excellent communication'],
      salary: { min: 110000, max: 145000, currency: 'USD' },
      postedDate: '2024-01-12T00:00:00.000Z',
      hiringManagerId: 'user-1',
      teamMemberIds: [],
      tags: ['product', 'strategy'],
    },
    {
      id: 'job-3',
      title: 'UX Designer',
      department: 'Design',
      location: 'San Francisco, CA',
      type: 'full_time',
      experienceLevel: 'mid',
      status: 'open',
      description: 'Join our design team to create beautiful, user-centered experiences.',
      requirements: ['Figma proficiency', 'Portfolio required', '3+ years experience'],
      salary: { min: 100000, max: 135000, currency: 'USD' },
      postedDate: '2024-01-15T00:00:00.000Z',
      hiringManagerId: 'user-1',
      teamMemberIds: [],
      tags: ['design', 'ux', 'figma'],
    },
    {
      id: 'job-4',
      title: 'Backend Engineer',
      department: 'Engineering',
      location: 'Remote',
      type: 'full_time',
      experienceLevel: 'senior',
      status: 'paused',
      description: 'Looking for a Backend Engineer with strong distributed systems experience.',
      requirements: ['Go or Rust experience', 'Kubernetes', 'PostgreSQL'],
      salary: { min: 140000, max: 180000, currency: 'USD' },
      postedDate: '2024-01-08T00:00:00.000Z',
      hiringManagerId: 'user-1',
      teamMemberIds: [],
      tags: ['backend', 'go', 'kubernetes'],
    },
    {
      id: 'job-5',
      title: 'Marketing Manager',
      department: 'Marketing',
      location: 'Austin, TX',
      type: 'full_time',
      experienceLevel: 'mid',
      status: 'draft',
      description: 'Drive marketing initiatives across digital and traditional channels.',
      requirements: ['5+ years marketing', 'SEO/SEM expertise', 'Data-driven mindset'],
      postedDate: '2024-01-18T00:00:00.000Z',
      hiringManagerId: 'user-1',
      teamMemberIds: [],
      tags: ['marketing', 'seo'],
    },
  ],
  candidates: [
    {
      id: 'cand-1',
      name: 'Sarah Chen',
      email: 'sarah.chen@email.com',
      phone: '+1 555-0101',
      location: 'San Francisco, CA',
      currentRole: 'Frontend Engineer at Stripe',
      appliedJobId: 'job-1',
      status: 'interview',
      applicationStatus: 'shortlisted',
      skills: ['React', 'TypeScript', 'CSS', 'GraphQL'],
      notes: 'Strong portfolio, excellent communication skills.',
      appliedDate: '2024-01-20T00:00:00.000Z',
      source: 'LinkedIn',
      rating: 4,
      tags: ['strong-candidate', 'frontend'],
    },
    {
      id: 'cand-2',
      name: 'Marcus Williams',
      email: 'marcus.w@email.com',
      phone: '+1 555-0102',
      location: 'New York, NY',
      currentRole: 'Product Manager at Airbnb',
      appliedJobId: 'job-2',
      status: 'screening',
      applicationStatus: 'reviewing',
      skills: ['Product Strategy', 'Analytics', 'Roadmapping', 'Agile'],
      notes: 'Great background in consumer products.',
      appliedDate: '2024-01-22T00:00:00.000Z',
      source: 'Referral',
      rating: 4,
      tags: ['product', 'consumer'],
    },
    {
      id: 'cand-3',
      name: 'Emily Rodriguez',
      email: 'emily.r@email.com',
      phone: '+1 555-0103',
      location: 'Austin, TX',
      currentRole: 'UX Designer at Figma',
      appliedJobId: 'job-3',
      status: 'offer',
      applicationStatus: 'shortlisted',
      skills: ['Figma', 'Prototyping', 'User Research', 'Design Systems'],
      notes: 'Exceptional portfolio, culture fit confirmed.',
      appliedDate: '2024-01-18T00:00:00.000Z',
      source: 'Portfolio site',
      rating: 5,
      tags: ['design', 'top-candidate'],
    },
    {
      id: 'cand-4',
      name: 'David Park',
      email: 'david.park@email.com',
      phone: '+1 555-0104',
      location: 'Seattle, WA',
      currentRole: 'Senior Engineer at AWS',
      appliedJobId: 'job-4',
      status: 'new',
      applicationStatus: 'applied',
      skills: ['Go', 'Kubernetes', 'PostgreSQL', 'Terraform'],
      notes: 'Impressive systems background.',
      appliedDate: '2024-01-25T00:00:00.000Z',
      source: 'Job board',
      rating: 3,
      tags: ['backend', 'devops'],
    },
    {
      id: 'cand-5',
      name: 'Lisa Thompson',
      email: 'lisa.t@email.com',
      phone: '+1 555-0105',
      location: 'Chicago, IL',
      currentRole: 'Marketing Lead at HubSpot',
      appliedJobId: 'job-1',
      status: 'rejected',
      applicationStatus: 'rejected',
      skills: ['SEO', 'Content Marketing', 'Analytics', 'Paid Ads'],
      notes: 'Good candidate but not the right fit for engineering role.',
      appliedDate: '2024-01-19T00:00:00.000Z',
      source: 'LinkedIn',
      rating: 2,
      tags: ['marketing'],
    },
    {
      id: 'cand-6',
      name: 'James Kim',
      email: 'james.kim@email.com',
      phone: '+1 555-0106',
      location: 'Remote',
      currentRole: 'Full Stack Developer at Shopify',
      appliedJobId: 'job-1',
      status: 'screening',
      applicationStatus: 'reviewing',
      skills: ['React', 'Node.js', 'Python', 'AWS'],
      notes: 'Versatile developer, good communication.',
      appliedDate: '2024-01-23T00:00:00.000Z',
      source: 'GitHub',
      rating: 4,
      tags: ['fullstack', 'frontend'],
    },
  ],
  interviews: [
    {
      id: 'int-1',
      candidateId: 'cand-1',
      jobId: 'job-1',
      type: 'technical',
      status: 'scheduled',
      scheduledAt: '2024-02-05T14:00:00.000Z',
      duration: 90,
      interviewerIds: ['user-1'],
      location: 'Zoom',
      notes: 'Focus on React architecture and TypeScript',
    },
    {
      id: 'int-2',
      candidateId: 'cand-2',
      jobId: 'job-2',
      type: 'hr',
      status: 'completed',
      scheduledAt: '2024-01-30T10:00:00.000Z',
      duration: 45,
      interviewerIds: ['user-1'],
      notes: 'Culture fit assessment - went well',
      rating: 4,
    },
    {
      id: 'int-3',
      candidateId: 'cand-3',
      jobId: 'job-3',
      type: 'onsite',
      status: 'completed',
      scheduledAt: '2024-01-28T09:00:00.000Z',
      duration: 180,
      interviewerIds: ['user-1'],
      notes: 'Full design challenge and team lunch',
      rating: 5,
    },
    {
      id: 'int-4',
      candidateId: 'cand-6',
      jobId: 'job-1',
      type: 'phone',
      status: 'scheduled',
      scheduledAt: '2024-02-07T11:00:00.000Z',
      duration: 30,
      interviewerIds: ['user-1'],
    },
  ],
  team: [
    {
      id: 'user-1',
      name: 'Alex Johnson',
      email: 'alex@company.com',
      role: 'admin',
      department: 'Engineering',
      isActive: true,
      joinedDate: '2022-01-15T00:00:00.000Z',
    },
    {
      id: 'user-2',
      name: 'Rachel Green',
      email: 'rachel@company.com',
      role: 'recruiter',
      department: 'HR',
      isActive: true,
      joinedDate: '2022-06-01T00:00:00.000Z',
    },
    {
      id: 'user-3',
      name: 'Tom Baker',
      email: 'tom@company.com',
      role: 'hiring_manager',
      department: 'Engineering',
      isActive: true,
      joinedDate: '2021-09-10T00:00:00.000Z',
    },
    {
      id: 'user-4',
      name: 'Nina Patel',
      email: 'nina@company.com',
      role: 'interviewer',
      department: 'Design',
      isActive: false,
      joinedDate: '2023-03-20T00:00:00.000Z',
    },
    {
      id: 'user-5',
      name: 'Chris Lee',
      email: 'chris@company.com',
      role: 'external',
      department: 'Consulting',
      isActive: true,
      joinedDate: '2023-11-01T00:00:00.000Z',
    },
  ],
};
