import type { AppState } from '@/types';

export function getSeedData(): AppState {
  const users = [
    {
      id: 'u1',
      name: 'Alex Rivera',
      email: 'alex@company.com',
      role: 'admin' as const,
      department: 'HR',
      joinedAt: '2023-01-10',
    },
    {
      id: 'u2',
      name: 'Jordan Smith',
      email: 'jordan@company.com',
      role: 'recruiter' as const,
      department: 'HR',
      joinedAt: '2023-03-15',
    },
    {
      id: 'u3',
      name: 'Morgan Lee',
      email: 'morgan@company.com',
      role: 'hiring_manager' as const,
      department: 'Engineering',
      joinedAt: '2022-08-01',
    },
    {
      id: 'u4',
      name: 'Casey Taylor',
      email: 'casey@company.com',
      role: 'interviewer' as const,
      department: 'Engineering',
      joinedAt: '2022-11-20',
    },
    {
      id: 'u5',
      name: 'Riley Johnson',
      email: 'riley@company.com',
      role: 'interviewer' as const,
      department: 'Product',
      joinedAt: '2023-06-01',
    },
  ];

  const defaultStages = [
    { id: 's1', name: 'Applied', order: 0, color: '#6c63ff', type: 'applied' as const },
    { id: 's2', name: 'Screening', order: 1, color: '#3b82f6', type: 'screening' as const },
    { id: 's3', name: 'Interview', order: 2, color: '#f59e0b', type: 'interview' as const },
    { id: 's4', name: 'Technical', order: 3, color: '#06b6d4', type: 'technical' as const },
    { id: 's5', name: 'Offer', order: 4, color: '#22c55e', type: 'offer' as const },
    { id: 's6', name: 'Hired', order: 5, color: '#22c55e', type: 'hired' as const },
  ];

  const jobs = [
    {
      id: 'j1',
      title: 'Senior Frontend Engineer',
      department: 'Engineering',
      location: 'Remote',
      type: 'full_time' as const,
      status: 'open' as const,
      description: 'We are looking for a Senior Frontend Engineer to join our growing team...',
      requirements: ['5+ years React', 'TypeScript expertise', 'Strong CSS skills', 'Team leadership experience'],
      salaryMin: 120000,
      salaryMax: 160000,
      currency: 'USD',
      createdAt: '2024-01-05',
      updatedAt: '2024-01-10',
      postedAt: '2024-01-10',
      hiringManagerId: 'u3',
      recruiterId: 'u2',
      stages: defaultStages,
      applicationCount: 12,
      openings: 2,
    },
    {
      id: 'j2',
      title: 'Product Designer',
      department: 'Design',
      location: 'New York, NY',
      type: 'full_time' as const,
      status: 'open' as const,
      description: 'Join our design team to craft beautiful, user-centric experiences...',
      requirements: ['3+ years product design', 'Figma proficiency', 'Design system experience', 'User research skills'],
      salaryMin: 90000,
      salaryMax: 120000,
      currency: 'USD',
      createdAt: '2024-01-12',
      updatedAt: '2024-01-15',
      postedAt: '2024-01-15',
      hiringManagerId: 'u3',
      recruiterId: 'u2',
      stages: defaultStages,
      applicationCount: 8,
      openings: 1,
    },
    {
      id: 'j3',
      title: 'DevOps Engineer',
      department: 'Engineering',
      location: 'San Francisco, CA',
      type: 'full_time' as const,
      status: 'open' as const,
      description: 'We need a DevOps engineer to help scale our infrastructure...',
      requirements: ['AWS/GCP experience', 'Kubernetes', 'CI/CD pipelines', 'Infrastructure as Code'],
      salaryMin: 110000,
      salaryMax: 150000,
      currency: 'USD',
      createdAt: '2024-01-20',
      updatedAt: '2024-01-22',
      postedAt: '2024-01-22',
      hiringManagerId: 'u3',
      recruiterId: 'u2',
      stages: defaultStages,
      applicationCount: 5,
      openings: 1,
    },
    {
      id: 'j4',
      title: 'Marketing Manager',
      department: 'Marketing',
      location: 'Remote',
      type: 'full_time' as const,
      status: 'draft' as const,
      description: 'Lead our marketing initiatives and grow brand awareness...',
      requirements: ['5+ years marketing', 'B2B SaaS experience', 'Data-driven mindset', 'Content strategy'],
      salaryMin: 85000,
      salaryMax: 110000,
      currency: 'USD',
      createdAt: '2024-02-01',
      updatedAt: '2024-02-01',
      hiringManagerId: 'u3',
      recruiterId: 'u2',
      stages: defaultStages,
      applicationCount: 0,
      openings: 1,
    },
    {
      id: 'j5',
      title: 'Backend Engineer',
      department: 'Engineering',
      location: 'Remote',
      type: 'full_time' as const,
      status: 'paused' as const,
      description: 'Build robust backend systems to power our platform...',
      requirements: ['Node.js or Go', 'PostgreSQL', 'REST/GraphQL APIs', 'Microservices'],
      salaryMin: 110000,
      salaryMax: 145000,
      currency: 'USD',
      createdAt: '2023-12-01',
      updatedAt: '2024-01-30',
      postedAt: '2023-12-05',
      hiringManagerId: 'u3',
      recruiterId: 'u2',
      stages: defaultStages,
      applicationCount: 20,
      openings: 2,
    },
  ];

  const candidates = [
    {
      id: 'c1',
      firstName: 'Emma',
      lastName: 'Wilson',
      email: 'emma.wilson@email.com',
      phone: '+1 555-0101',
      location: 'Austin, TX',
      currentTitle: 'Frontend Engineer',
      currentCompany: 'TechCorp',
      linkedinUrl: 'https://linkedin.com/in/emmawilson',
      source: 'linkedin' as const,
      tags: ['React', 'TypeScript', 'Strong'],
      createdAt: '2024-01-11',
      updatedAt: '2024-01-15',
      applications: [],
    },
    {
      id: 'c2',
      firstName: 'Liam',
      lastName: 'Chen',
      email: 'liam.chen@email.com',
      phone: '+1 555-0102',
      location: 'San Francisco, CA',
      currentTitle: 'Senior Developer',
      currentCompany: 'StartupXYZ',
      source: 'portal' as const,
      tags: ['React', 'Node.js'],
      createdAt: '2024-01-12',
      updatedAt: '2024-01-18',
      applications: [],
    },
    {
      id: 'c3',
      firstName: 'Sophia',
      lastName: 'Martinez',
      email: 'sophia.m@email.com',
      phone: '+1 555-0103',
      location: 'New York, NY',
      currentTitle: 'UX Designer',
      currentCompany: 'DesignStudio',
      linkedinUrl: 'https://linkedin.com/in/sophiamartinez',
      source: 'job_board' as const,
      tags: ['Figma', 'UX Research', 'Design Systems'],
      createdAt: '2024-01-16',
      updatedAt: '2024-01-20',
      applications: [],
    },
    {
      id: 'c4',
      firstName: 'Noah',
      lastName: 'Brown',
      email: 'noah.brown@email.com',
      location: 'Remote',
      currentTitle: 'DevOps Engineer',
      currentCompany: 'CloudCo',
      source: 'referral' as const,
      tags: ['AWS', 'Kubernetes', 'Terraform'],
      createdAt: '2024-01-21',
      updatedAt: '2024-01-24',
      applications: [],
    },
    {
      id: 'c5',
      firstName: 'Ava',
      lastName: 'Davis',
      email: 'ava.davis@email.com',
      phone: '+1 555-0105',
      location: 'Chicago, IL',
      currentTitle: 'Product Designer',
      currentCompany: 'AgencyABC',
      source: 'manual' as const,
      tags: ['Figma', 'Prototyping'],
      createdAt: '2024-01-22',
      updatedAt: '2024-01-25',
      applications: [],
    },
    {
      id: 'c6',
      firstName: 'Ethan',
      lastName: 'Garcia',
      email: 'ethan.garcia@email.com',
      location: 'Seattle, WA',
      currentTitle: 'Full Stack Developer',
      currentCompany: 'MidTech',
      source: 'linkedin' as const,
      tags: ['React', 'TypeScript', 'AWS'],
      createdAt: '2024-01-25',
      updatedAt: '2024-01-28',
      applications: [],
    },
    {
      id: 'c7',
      firstName: 'Olivia',
      lastName: 'Thompson',
      email: 'olivia.t@email.com',
      phone: '+1 555-0107',
      location: 'Boston, MA',
      currentTitle: 'Frontend Lead',
      currentCompany: 'BigCorp',
      source: 'job_board' as const,
      tags: ['React', 'Leadership', 'TypeScript'],
      createdAt: '2024-01-28',
      updatedAt: '2024-02-01',
      applications: [],
    },
  ];

  const applications = [
    {
      id: 'a1',
      candidateId: 'c1',
      jobId: 'j1',
      stage: 'interview' as const,
      status: 'active' as const,
      appliedAt: '2024-01-11',
      updatedAt: '2024-01-18',
      notes: [
        {
          id: 'n1',
          authorId: 'u2',
          content: 'Strong React background, great communication skills.',
          createdAt: '2024-01-15',
          type: 'comment' as const,
        },
      ],
      score: 85,
      assignedTo: 'u2',
    },
    {
      id: 'a2',
      candidateId: 'c2',
      jobId: 'j1',
      stage: 'screening' as const,
      status: 'active' as const,
      appliedAt: '2024-01-12',
      updatedAt: '2024-01-16',
      notes: [],
      score: 72,
      assignedTo: 'u2',
    },
    {
      id: 'a3',
      candidateId: 'c3',
      jobId: 'j2',
      stage: 'technical' as const,
      status: 'active' as const,
      appliedAt: '2024-01-16',
      updatedAt: '2024-01-22',
      notes: [
        {
          id: 'n2',
          authorId: 'u3',
          content: 'Excellent portfolio. Has experience with design systems at scale.',
          createdAt: '2024-01-20',
          type: 'comment' as const,
        },
      ],
      score: 91,
      assignedTo: 'u2',
    },
    {
      id: 'a4',
      candidateId: 'c4',
      jobId: 'j3',
      stage: 'applied' as const,
      status: 'active' as const,
      appliedAt: '2024-01-21',
      updatedAt: '2024-01-21',
      notes: [],
      score: 78,
      assignedTo: 'u2',
    },
    {
      id: 'a5',
      candidateId: 'c5',
      jobId: 'j2',
      stage: 'offer' as const,
      status: 'active' as const,
      appliedAt: '2024-01-22',
      updatedAt: '2024-01-30',
      notes: [],
      score: 88,
      assignedTo: 'u2',
      offerAmount: 105000,
      offerCurrency: 'USD',
      offerDate: '2024-01-30',
    },
    {
      id: 'a6',
      candidateId: 'c6',
      jobId: 'j1',
      stage: 'applied' as const,
      status: 'active' as const,
      appliedAt: '2024-01-25',
      updatedAt: '2024-01-25',
      notes: [],
      score: 65,
      assignedTo: 'u2',
    },
    {
      id: 'a7',
      candidateId: 'c7',
      jobId: 'j1',
      stage: 'offer' as const,
      status: 'active' as const,
      appliedAt: '2024-01-28',
      updatedAt: '2024-02-01',
      notes: [
        {
          id: 'n3',
          authorId: 'u4',
          content: 'Outstanding technical skills. Recommend for offer.',
          createdAt: '2024-01-31',
          type: 'interview_note' as const,
        },
      ],
      score: 95,
      assignedTo: 'u2',
      offerAmount: 155000,
      offerCurrency: 'USD',
      offerDate: '2024-02-01',
    },
  ];

  const interviews = [
    {
      id: 'i1',
      applicationId: 'a1',
      candidateId: 'c1',
      jobId: 'j1',
      type: 'video' as const,
      status: 'scheduled' as const,
      scheduledAt: '2024-02-10T14:00:00Z',
      duration: 60,
      interviewers: ['u3', 'u4'],
      meetingLink: 'https://meet.google.com/abc-defg-hij',
      createdAt: '2024-01-20',
    },
    {
      id: 'i2',
      applicationId: 'a3',
      candidateId: 'c3',
      jobId: 'j2',
      type: 'technical' as const,
      status: 'completed' as const,
      scheduledAt: '2024-01-25T10:00:00Z',
      duration: 90,
      interviewers: ['u4', 'u5'],
      meetingLink: 'https://zoom.us/j/123456789',
      notes: 'Strong technical performance. Design challenge completed well.',
      feedback: [
        {
          interviewerId: 'u4',
          rating: 5 as const,
          recommendation: 'strong_yes' as const,
          notes: 'Excellent problem solving and design thinking.',
          submittedAt: '2024-01-25',
        },
      ],
      createdAt: '2024-01-18',
    },
    {
      id: 'i3',
      applicationId: 'a7',
      candidateId: 'c7',
      jobId: 'j1',
      type: 'panel' as const,
      status: 'completed' as const,
      scheduledAt: '2024-01-31T15:00:00Z',
      duration: 120,
      interviewers: ['u3', 'u4', 'u5'],
      meetingLink: 'https://teams.microsoft.com/meeting/123',
      feedback: [
        {
          interviewerId: 'u3',
          rating: 5 as const,
          recommendation: 'strong_yes' as const,
          notes: 'Leadership experience is exceptional.',
          submittedAt: '2024-01-31',
        },
        {
          interviewerId: 'u4',
          rating: 4 as const,
          recommendation: 'yes' as const,
          notes: 'Strong technical skills, good culture fit.',
          submittedAt: '2024-01-31',
        },
      ],
      createdAt: '2024-01-25',
    },
  ];

  const emailTemplates = [
    {
      id: 'et1',
      name: 'Application Received',
      subject: 'We received your application for {{job_title}}',
      body: 'Hi {{candidate_name}},\n\nThank you for applying for the {{job_title}} position at our company. We have received your application and will review it shortly.\n\nBest regards,\nThe Recruiting Team',
      stage: 'applied' as const,
      isActive: true,
    },
    {
      id: 'et2',
      name: 'Phone Screen Invite',
      subject: 'Next Steps: Phone Screen for {{job_title}}',
      body: 'Hi {{candidate_name}},\n\nWe were impressed with your application and would love to schedule a quick phone screen. Please use the link below to book a time.\n\n{{scheduling_link}}\n\nBest regards,\nThe Recruiting Team',
      stage: 'screening' as const,
      isActive: true,
    },
    {
      id: 'et3',
      name: 'Interview Invitation',
      subject: 'Interview Invitation: {{job_title}}',
      body: 'Hi {{candidate_name}},\n\nWe are pleased to invite you for an interview for the {{job_title}} role. Details will be shared shortly.\n\nBest regards,\nThe Recruiting Team',
      stage: 'interview' as const,
      isActive: true,
    },
    {
      id: 'et4',
      name: 'Offer Letter',
      subject: 'Offer of Employment: {{job_title}}',
      body: 'Hi {{candidate_name}},\n\nWe are thrilled to offer you the position of {{job_title}}. Please find the offer details attached.\n\nBest regards,\nThe Recruiting Team',
      stage: 'offer' as const,
      isActive: true,
    },
    {
      id: 'et5',
      name: 'Rejection Email',
      subject: 'Your application for {{job_title}}',
      body: 'Hi {{candidate_name}},\n\nThank you for your interest in the {{job_title}} position. After careful consideration, we have decided to move forward with other candidates. We encourage you to apply for future openings.\n\nBest regards,\nThe Recruiting Team',
      stage: 'rejected' as const,
      isActive: true,
    },
  ];

  return {
    currentUser: users[0],
    users,
    jobs,
    candidates,
    applications,
    interviews,
    emailTemplates,
  };
}
